[workspace]
changelog_path = "./CHANGELOG.md"

publish = false            # don't publish to crates.io
git_tag_enable = false     # default no tags for workspace crates
git_release_enable = false # default no gh release for workspace crates
release = false            # default no release for workspace crates
release_always = false     # do not publish on every commit to main
semver_check = false       # do not semver

# visual release/pr config
git_release_type = "auto"   # mark as pre-release on gh if rc, otherwise normal release
pr_labels = ["autorelease"]
# TODO: more robust way to query version change than array index 0
pr_body = """
# **Vantablock**: {{ releases[0].previous_version }} -> {{ releases[0].next_version }}

{{ releases[0].changelog }}
"""

# runner package is the main release entrypoint
[[package]]
name = "vantablock-runner"
release = true
# TODO: can't get git_only to work, https://github.com/release-plz/release-plz/issues/2595
# waiting on https://github.com/release-plz/release-plz/pull/2652 to be merged, seems like the fix
# git_only = true            # rely on git tags instead of crates.io
git_tag_enable = true                           # create tags
git_release_enable = true                       # make a gh release
git_release_name = "Vanta🅱️lock v{{ version }}" # release with game name since single-release
git_tag_name = "v{{ version }}"                 # tag with only version since single-release

[changelog]
# template for the changelog body
# https://release-plz.dev/docs/extra/single-changelog
body = """
{% if version %}
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{commit.scope}})* {% endif %}{% if commit.breaking %}**BREAKING** {% endif %}{{ commit.message }}
{%- endfor -%}
{% endfor -%}
"""
# remove the leading and trailing whitespace from the templates
trim = true

# regex for parsing and grouping commits
commit_parsers = [
  { message = "^feat", group = "Features 🚀" },
  { message = "^fix", group = "Bug Fixes 🐛" },
  { message = "^perf", group = "Performance Improvements 🧠" },
  { message = "^docs", group = "Documentation 📜" },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^refactor", skip = true },
  { message = "^style", skip = true },
  { message = "^test", skip = true },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# sort the commits inside sections by message
sort_commits = "oldest"
