use crate::world::chunk::components::GeneratedChunkComponentBundle;
use bevy::ecs::prelude::Component;
use crossbeam::channel::Receiver;
use shared::world::chunk::ChunkLod;

/// Marks a chunk loading task in the simulation world that returns nothing.
#[derive(Component)]
pub struct ChunkGenerationTaskComponent {
    pub receiver: Receiver<GeneratedChunkComponentBundle>,
}

/// Marks that a chunk needs to have its data generated by the terrain generator.
#[derive(Component)]
pub struct NeedsGenerating {
    pub lod: ChunkLod,
}
